export const EVIDENCE_TIERS = {
  TIER1: {
    id: 'tier1',
    title: 'Tier 1: Strong Evidence',
    points: 15,
    description: 'Official documents from organizations that conduct identity/address checks.',
    color: '#1B5E20',
  },
  TIER2: {
    id: 'tier2',
    title: 'Tier 2: Acceptable Evidence',
    points: 7,
    description: 'Dated domestic bills or receipts for joint purchases.',
    color: '#E65100',
  },
  TIER3: {
    id: 'tier3',
    title: 'Tier 3: Supporting Evidence',
    points: 3,
    description: 'Supplementary evidence that supports stronger documentation.',
    color: '#0D47A1',
  },
};

export const EVIDENCE_ITEMS = [
  // Tier 1
  {
    id: 'marriage_cert',
    tier: 'tier1',
    label: 'Marriage or Civil Partnership Certificate',
    icon: 'certificate',
    description: 'A legal document that proves your marriage or civil partnership.',
    specifics: 'Must be a certified copy and legally recognized in the country of issue. If not in English, a certified translation is required.',
  },
  {
    id: 'joint_mortgage_tenancy',
    tier: 'tier1',
    label: 'Joint Mortgage or Tenancy Agreement',
    icon: 'home',
    description: 'Legal document showing shared responsibility for your home.',
    specifics: 'Should show both names and the address of the property you share. Current agreements or statements from the last 2 years are strongest.',
  },
  {
    id: 'joint_utility_bills',
    tier: 'tier1',
    label: 'Joint Utility Bills (Gas, Water, Electric, Council Tax)',
    icon: 'lightning-bolt',
    description: 'Official bills for household services in both names.',
    specifics: 'Must be dated. Home Office prefers bills spread over the last 2 years to show a history of living together.',
  },
  {
    id: 'joint_bank_statements',
    tier: 'tier1',
    label: 'Joint Bank Statements',
    icon: 'bank',
    description: 'Bank account statements showing both names at the same address.',
    specifics: 'Showing regular household transactions (rent, bills) from this account makes it even stronger evidence of shared life.',
  },
  {
    id: 'official_correspondence',
    tier: 'tier1',
    label: 'Official Correspondence (NHS, HMRC, DVLA)',
    icon: 'mail',
    description: 'Letters from government departments or the NHS sent to you both.',
    specifics: 'These are highly trusted as they verify your address through official channels.',
  },
  {
    id: 'birth_cert_children',
    tier: 'tier1',
    label: 'Birth Certificates of Children',
    icon: 'baby-carriage',
    description: 'Official birth certificates naming both of you as parents.',
    specifics: 'Very strong Tier 1 evidence of a committed family relationship.',
  },
  {
    id: 'life_insurance',
    tier: 'tier1',
    label: 'Life Insurance / Pension Beneficiary',
    icon: 'shield-account',
    description: 'Official documents naming your partner as a beneficiary.',
    specifics: 'Shows significant long-term financial commitment and shared planning.',
  },
  // Tier 2
  {
    id: 'other_domestic_bills',
    tier: 'tier2',
    label: 'Other Domestic Bills (Vet, home repairs)',
    icon: 'file-document',
    description: 'Bills for household services not covered in Tier 1.',
    specifics: 'Includes things like TV license, broadband, or vet bills if you have a pet together.',
  },
  {
    id: 'joint_purchases',
    tier: 'tier2',
    label: 'Receipts for Significant Joint Purchases',
    icon: 'cart',
    description: 'Receipts for large items bought together (e.g., furniture).',
    specifics: 'Stronger if both names appear on the delivery note or the invoice.',
  },
  {
    id: 'car_insurance',
    tier: 'tier2',
    label: 'Car Insurance (Joint or same address)',
    icon: 'car',
    description: 'Insurance documents showing you both drive or live together.',
    specifics: 'A joint car insurance policy or separate policies registered at the same address.',
  },
  {
    id: 'driving_license_address',
    tier: 'tier2',
    label: 'Driving Licenses (Same address)',
    icon: 'card-account-details',
    description: 'Government IDs showing you both reside at the same property.',
    specifics: 'A simple way to verify shared residence through an official ID.',
  },
  // Tier 3
  {
    id: 'letters_support',
    tier: 'tier3',
    label: 'Letters of Support (Friends/Family)',
    icon: 'account-group',
    description: 'Statements from people who know you as a couple.',
    specifics: 'Should include how they know you and their observations of your relationship. Include a copy of their ID if possible.',
  },
  {
    id: 'written_statements',
    tier: 'tier3',
    label: 'Written Statements (Relationship History)',
    icon: 'fountain-pen-tip',
    description: 'Your own account of how your relationship developed.',
    specifics: 'Detail key milestones: when you met, when you moved in, and your future plans.',
  },
  {
    id: 'photographs',
    tier: 'tier3',
    label: 'Photographs together',
    icon: 'camera',
    description: 'Photos from different times and places during your relationship.',
    specifics: 'Best to include a variety: showing you with each other\'s families, at events, or traveling together.',
  },
  {
    id: 'comms_records',
    tier: 'tier3',
    label: 'Communication Records (Chat logs, emails)',
    icon: 'chat',
    description: 'Evidence of regular contact when living apart.',
    specifics: 'Screenshots from WhatsApp, logs of video calls, or email chains. Focus on continuity over a long period.',
  },
  {
    id: 'travel_history',
    tier: 'tier3',
    label: 'Travel History (Flight bookings, hotels)',
    icon: 'airplane',
    description: 'Evidence of trips taken together or visits to see each other.',
    specifics: 'Flight confirmations, hotel bookings, or passport stamps showing travel on the same dates.',
  },
  {
    id: 'support_letter_partner',
    tier: 'tier3',
    label: 'Detailed Support Letter from UK Partner',
    icon: 'heart-outline',
    description: 'A formal letter from the sponsor supporting the application.',
    specifics: 'The sponsor should confirm their commitment and describe their life with the applicant.',
  },
];
